server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry:8761/eureka}
  instance:
    prefer-ip-address: on

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin1:admin1@dbproyect.sklmn.mongodb.net/DbProyect?retryWrites=true&w=majority