eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.0.200:8761/eureka}
  instance:
    prefer-ip-address: on

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb+srv://admin1:admin1@dbproyect.sklmn.mongodb.net/DbProyect?retryWrites=true&w=majority