server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry:8080/eureka}
  instance:
    prefer-ip-address: on

spring:
  cloud:
    gateway:
      filter:
        redirect-to:
          enabled: off
      discovery:
        locator:
          enabled: on
      routes:
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/**

        - id: customer-service
          uri: lb://customer
          predicates:
            - Path=/customers/**

        - id: account-service
          uri: lb://account
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://transaction
          predicates:
            - Path=/transactions/**

        - id: credit-service
          uri: lb://credit
          predicates:
            - Path=/credits/**
