eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.0.200:8761/eureka}
  instance:
    prefer-ip-address: on

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: on
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credits/**
